modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL = "https://github.com/GreatOrator/TolkienTweaks-Mobs-Edition/issues"
license="MIT License"

[[mods]]
	modId="tolkienmobs"
	displayName="Tolkien Tweaks (Mobs Edition)"
    version="${version}"
    credits = "Brandon3055 for all of his help on the more difficult stuff"
    logoFile = "logo.png"
    authors="GreatOrator"
	description='''
	Collection of items, blocks, mobs, etc for both increased play and map making
	'''
    updateJSONURL=""
[[dependencies.tolkienmobs]]
    modId="forge"
    mandatory=true
    versionRange="[36.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tolkienmobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tolkienmobs]]
    modId="codechickenlib"
    mandatory=true
    versionRange="${ccl_version}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.tolkienmobs]]
    modId="brandonscore"
    mandatory=true
    versionRange="[${bcore_version},)"
    ordering="AFTER"
    side="BOTH"